version: '3.8'

services:
  spring_app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: postgres:14.0
    ports: 
      - 8010:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bookmarks
      - POSTGRES_PASSWORD=bookmarks
      - POSTGRES_DB=bookmarks
    restart: unless-stopped

volumes:
  postgres_data:
