version: '3.8'

services:
  spring_app:
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: postgres:14.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bookmarks
      - POSTGRES_PASSWORD=bookmarks
      - POSTGRES_DB=bookmarks
    restart: unless-stopped

volumes:
  postgres_data:
